### ISSUE TITLE
 getTrackDataMobileById

### ISSUE THREAD

**Issue by 89z** [L0v4iy/deezer-api-client#1]
It seems this is never used:

https://github.com/L0v4iy/deezer-api-client/blob/391a10b0a0476b52ab3c9f572144754e946a1470/src/main/java/com/L0v4iy/deezer/client/DeezerApiWrapper.java#L88-L128

and from what I can tell, it doesnt actually work anymore. It might be good to remove it, unless we know it still works.

**Comment by L0v4iy** [comment]
Fixed

**Comment by 89z** [comment]
I found out that this does still work, but you need to use it like this:

~~~
deezer.getUserData -> song.getData
~~~

and you also need the ARL cookie.

**Comment by L0v4iy** [comment]
Maybe I dont understand but I use  `deezer.getUserData` on login and update api token _every 1 hour_. 
If you mean `query.setParameter("method", "song_getData");` I think there is an error `song.getData` . 
But the biggest issue is _Invalid cookie header_ error. I tried to change
`CookieSpecs` in 
`RequestConfig globalConfig = RequestConfig.custom()
                .setCookieSpec(CookieSpecs.DEFAULT)
                .build();`
but on the other values client dont log in deezer.

**Comment by 89z** [comment]
If you are going to use the `song.getData`, it works like this:

First get ARL cookie. This last days or longer, so dont need to update every
hour.

Then make `deezer.getUserData` using that cookie.

Then make `song.getData` request.
